#pragma once

#include "SocksHttpBean.hpp"
#include "ShadowSocksBean.hpp"
#include "ChainBean.hpp"
#include "LoadBalanceBean.hpp"
#include "VMessBean.hpp"
#include "TrojanVLESSBean.hpp"
#include "NaiveBean.hpp"
#include "QUICBean.hpp"
#include "CustomBean.hpp"
#include "AnyTLSBean.hpp"
#include "ShadowTLSBean.hpp"
#include "SSHBean.hpp"
#include "HysteriaBean.hpp"
